[build]
command = "node build-replit.js"

[run]
command = "node dist/server.js"

[deployment]
build = "node build-replit.js"
run = "node dist/server.js"
publicDir = "dist"

[env]
NODE_ENV = "production"

[deployment.env]
NODE_ENV = "production"